services:
  backend-api:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./storage:/data_storage
    # Esto evita que se borren archivos si el contenedor se detiene
    env_file:
      - ./backend/.env

  frontend-app:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    depends_on:
      - backend-api
